### ISSUE TITLE
did not send notification by grpc(again)

### ISSUE THREAD

**Issue by oybekmuzropov** [appleboy/gorush#483] opened 2020-03-13 12:04 UTC
@appleboy I did not send notification by GRPC.  gorush/worker.go file has SendNotification(req PushNotification) func. In this func, read req.ctx.Done(). But ctx did not set. I fixed it, but did not send pull request. Please fix this bug.

**Comment by slimus** [comment] 2020-03-13 15:50
duplicate of #446

**Closed** 2020-03-13 16:00 UTC
