### ISSUE TITLE
Not sure how to send sound in ios app notification?

### ISSUE THREAD

**Issue by andthereitgoes** [appleboy/gorush#389] opened 2018-12-21 15:43 UTC
Hi @appleboy 
I am trying to send default sound in the app notification for ios and looked at your documentation. The apple documentation expects it to be a string https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html

In your gorush README it is expected as an `interface{}` but in grpc proto file https://github.com/appleboy/gorush/blob/master/rpc/proto/gorush.proto, I am seeing that you are sending sound as a string. 

So I am confused what is it. Beacuse when I send sound as string in the `api/push` POST body I don't see it in the app notification payload. But when I send the sound as an object in the `api/push` POST body (as below) I am seeing it in app notification payload within the `aps` key but it does work and doesn't play the sound. 

What am I doing wrong? 

```
{
    "notifications": [
        {
            "platform": 1,
            "message": "test message with threadid",
            "badge": 3,
            "alert": {
                "title": "New offer",
                "body": "test message with threadid"
            },
            "sound": {
                "volume": 1,
                "name": "default",
                "critical": 1
            },
            "data": {
                "name": "John Doe",
                "id": "b48edd23-04b3-11e9-9d2d-66a036430288"
            }
			"threadID": "b48edd23-04b3-11e9-9d2d-66a036430288"
        }
    ]
}
```

**Comment by andthereitgoes** [comment] 2018-12-28 14:55
@appleboy any update on this one?

**Comment by dj95** [comment] 2019-03-01 09:13
Hi. I've experienced basically the same issue that you described. The problem is in the code, as the sound-implementation does not hand the string as sound over to apple. If a sound is specified via its name(with the 'name'-key https://github.com/appleboy/gorush/blob/master/gorush/notification.go#L91) the sound struct is created, too. As apple only uses the sound dict in the request for critical notifications, only the critical ones will use the sound. Please take a look on this pull request, where I fixed the issue.

https://github.com/appleboy/gorush/pull/394

With this fix you just need to set e.g. "default" as value for "sound" and you phone will ring :)

**Comment by appleboy** [comment] 2019-03-01 23:29
@dj95 Thanks for your PR. I will take it and merge as soon as possible.

**Comment by appleboy** [comment] 2019-03-13 16:02
Closed. #394 already merged

**Closed by appleboy** 2019-03-13 16:02 UTC
